version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    image: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - migration
  migration:
    build: .
    image: app
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py addadmin"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db