version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  web:
    image: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - migration
  migration:
    build: .
    image: app
    command: bash -c "python manage.py migrate"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db